name: Deploy Admin Panel

on:
  push:
    branches:
      - main  # Change this if you use a different branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/onpoint/admin-panel
            
            echo "Pulling latest changes..."
            git pull origin main  # Change branch if needed
            
            echo "Checking if container exists..."
            if [ "$(docker ps -aq -f name=admin-panel)" ]; then
              echo "Stopping and removing old container..."
              docker stop admin-panel
              docker rm admin-panel
            else
              echo "No existing container found, skipping removal."
            fi

            echo "Building new Docker image..."
            docker build -t admin-panel:latest .

            echo "Running new container..."
            docker run -d --name admin-panel --restart unless-stopped -p 9000:9000 admin-panel:latest

            echo "Cleaning up unused Docker images..."
            docker image prune -f

            echo "Deployment completed successfully!"
